### PR TITLE
Add "color" module & sort registry entries alphabetically

### PR DESCRIPTION
**Pull request by vulpivia**
I added the [color](https://github.com/pegasus-toolset/color) module v0.1.0 and sorted all packages alphabetically by their name. If you don't want that, I can create another pull request with just the first commit.

### CODE REVIEW

**Comment by nedpals** [comment]
Arranging packages is totally unnecessary since it's unavoidable to get cluttered if there are new packages submitted. :smile:

**Comment by vulpivia** [comment]
True, but it didn't take much time. Is my submission okay?

**Comment by nedpals** [comment]
I'm on mobile right now but so far it's good 👍

**Comment by nedpals** [comment]
@Acid147 I'll have to add your module manually. I'll close this.

**Pull request closed without merging**
